# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62136289271b5a157ad0ede35c654c858f5e6393c908c5b88d5cc8f0d7879e75c91d944091f17dd860601f077fc06638399a5c49e4ea4ce1c93fe011c9a5af6a

test:
  secret_key_base: 94ebf5e05fb2ea1eba0bc79c5b462a423f2a962a73af7f2c822c775fcc6c0747f39174dd5222227475e184321984ecd39d4b48f9412e7e0a316109905823bfbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
